### ISSUE TITLE
Timer causes high CPU usage

### ISSUE THREAD

**Issue by minorsecond** [minorsecond/Timeclock#16]

**Comment by minorsecond** [comment]
Moved time.sleep() to correct indentation level. 1 second resolution seems reasonable.

**Comment by minorsecond** [comment]
Reopened as threaded version of timer causes high CPU usage and since threading will be used ultimately, need to find a fix.

**Comment by NotTheEconomist** [comment]
If we don't need a constantly running timer, there's no great reason to be running it in a thread. Possibly just store start time, and only check end time when prompted from the menu. App then should consume zero CPU while waiting on user input at main menu.

Pros:
* App consumes nearly no resources while waiting for user input
* Simplifies control flow by cutting out the thread
Cons:
* If computer crashes or application unexpectedly quits, no time is recorded

**Comment by minorsecond** [comment]
You may be on to something with your time management idea, and it sounds like it would be more simple to implement than trying to balance CPU usage and having a running timer. Could also maker it easier to query previous hours worked for a project and anything else.

**Comment by NotTheEconomist** [comment]
Recommend closing this issue since we've moved away from the threaded timer approach.
