### ISSUE TITLE
Timer-thread: Timer breaks almost immediately after running.

### ISSUE THREAD

**Issue by minorsecond** [minorsecond/Timeclock#21]
Timer runs one iteration and quits. Looks like the "what are you doing" menu is being printed immediately, causing the timer to stop.

**Comment by minorsecond** [comment]
Timer is still running in background. This may actually be better as it is less "noisy" and would squash the urge to keep an eye on the clock.

"it's not a bug, it's a feature!"

**Comment by NotTheEconomist** [comment]
Yes in windows there's no great way to "overwrite" the screen to update the timer, other than `os.system('cls'); func_to_redraw_whole_screen()`. There's no way to blit the terminal like you can do on *nix.
