### ISSUE TITLE
Incompatible with Python 3

### ISSUE THREAD

**Issue by minorsecond** [minorsecond/Timeclock#22]
Currently writing on Python 2 interpreter. Will want to add Python 3 support in the future, after a working script is written.

**Comment by NotTheEconomist** [comment]
Currently Python3 support should be *really* easy. Change all the `print "blah blah"` print statements to `print("blah blah")` and add `from __future__ import print_function` to the imports.

**Comment by minorsecond** [comment]
Gave it a quick run-through and getting a lot of

"AttributeError: 'NoneType' object has no attribute 'format'"

Has something to do with the way the variables are being printed.
"print("\nCurrent Job: {0}, started at {1}.").format(project_name, clock_in)"

print(project_name) gives output, so it's being assigned data. Hmm.

**Comment by minorsecond** [comment]
Quick run-through,changing those print statements. 

Getting a cryptic error:

  File "tc.py", line 426
    print("PYPER Timesheet Utility \n \n"
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 11-12: malformed \N character escape

Tried moving \n around, nothing. Not much online about this error message.

**Comment by NotTheEconomist** [comment]
first issue is that it should be `print("\nCurrent Job: {0}, started at {1}.".format(project_name, clock_in)")`. `print` is a function that returns `None`. You want to call `format` from the string inside that function. Second issue is probably an unclosed paren? Maybe? I don't have time to look at codebase atm

**Comment by minorsecond** [comment]
Sorry I changed that - realized it was a stupid mistake I had made.

**Comment by minorsecond** [comment]
Syntax error fixed in Python3 branch. Runs in Python 3 but not 2.7 - need to find out solution to "builtins" module - which is named "__builtin__" in Python 2.

**Comment by minorsecond** [comment]
Builtin problem fixed - now getting error when running in Python 2:

File "tc.py", line 442, in main_menu
    if answer.lower() in {'1', '1.'}:
AttributeError: 'int' object has no attribute 'lower'

**Comment by NotTheEconomist** [comment]
Ah yes, user input. Python2 uses `raw_input` to get a string from the user and `input` to get actionable code from the user. Python3 doesn't use `raw_input` at all, and `input` gets a string. Wherever you do the version check, if you do `if py_version == python_2: input = raw_input` everything should be hunky dory.
